### ISSUE TITLE
Support for dark mode

### ISSUE THREAD

**Issue by brentkozjak** [tailwindcss/typography#13]
Firstly, this tailwind plugin is awesome!  Well done!

I'm using a "dark mode" tailwindcss plugin (https://github.com/ChanceArthur/tailwindcss-dark-mode), and it would be great to support something like this using this typography plugin.  From the documentation, I can see that it's simple enough to modify the styles in the `tailwind.config.js` file - but can we use this in conjunction with a dark mode parent class to provide both light and dark styles?

Thanks!

**Comment by adamwathan** [comment]
Hey! You can generate dark mode versions using that plugin by following the plugin instructions for enabling variants:

```js
variants: {
  typography: ['responsive', 'dark'],
}
```

The typography plugin will respect any variants you enable 👍

**Comment by ndrbrt** [comment]
Hey @adamwathan, that's what I did, yet some issues are still there: I wanted to change the text color when in dark mode, but was only able to get the regular text to change; every text related tag like h1, b, etc. remains the same as in light mode.

Here is my `tailwind.config.js`:
```js
module.exports = {
    theme: {
      darkSelector: '.dark-mode',
      typography: (theme) => ({
        'xs': {
          css: {
            h1: {
              fontSize: '1.75rem'
            }
          }
        },
        'dark': {
          css: {
            color: theme('colors.gray.300'),
            h1: {
              color: theme('colors.gray.400'),
            }
          }
        }
      })
    },
    variants: {
      typography: ['responsive', 'dark']
    },
    plugins: [
      require('tailwindcss-dark-mode')(),
      require('@tailwindcss/typography'),
    ]
  }
```

Then, in my component, I do something like:
```vue
<section v-html="compiledMarkdown" class="prose prose-xs dark:prose-dark" />
```

Note: if i add the class `prose-dark` without the `dark:` variant, it works fine (e.g. h1 changes its color too)

**Comment by mrkrstphr** [comment]
@ndrbrt Did you ever get this to work? I'm encountering the exact same problem. `dark:prose-dark` only changes regular text, not headings, etc. `prose-dark` by itself works fine.

**Comment by ndrbrt** [comment]
@mrkrstphr After spending way too much time on this, I gave up and wrote my custom (s)css.
Not the best solution maybe, but for now it just works.

Here's my custom scss file `prose_dark_mode.scss`:

```scss
/* 
 * 
 * For some reason, setting the dark mode for the "prose" in tailwind.config.js
 * did not work properly.
 * See: https://github.com/tailwindlabs/tailwindcss-typography/issues/13#issuecomment-661678512
 * See also: https://github.com/adamwathan/tailwindcss-dark-mode-prototype
 * 
 * The classes/rules are inspired by:
 * https://github.com/adamwathan/tailwindcss-dark-mode-prototype/blob/master/tailwind.config.js
 * (below is reported the concerned part of the file, for convenience)
 * ```js
 *    dark: {
        css: {
          color: theme('colors.gray.300'),
          '[class~="lead"]': {
            color: theme('colors.gray.400'),
          },
          blockquote: {
            color: theme('colors.gray.300'),
            borderLeftColor: theme('colors.gray.700'),
          },
          hr: {
            borderTopColor: theme('colors.gray.800'),
          },
          strong: {
            color: theme('colors.white'),
          },
          'figure figcaption': {
            color: theme('colors.gray.500'),
          },
          a: {
            color: theme('colors.white'),
          },
          th: {
            color: theme('colors.white'),
          },
          'h1, h2, h3, h4': {
            color: theme('colors.white'),
          },
          code: {
            color: theme('colors.gray.300'),
          },
          'code:before': {
            color: theme('colors.gray.300'),
          },
          'code:after': {
            color: theme('colors.gray.300'),
          },
          'ol > li:before': {
            color: theme('colors.gray.400'),
          },
          'ul > li:before': {
            backgroundColor: theme('colors.gray.600'),
          },
        },
      }
 * ```
 * 
 */

.dark-mode .prose {
    @apply text-gray-300;

    &[class~="lead"] {
        @apply text-gray-400;
    }

    & blockquote {
        @apply text-gray-300;
        @apply border-gray-700;
        border-top-color: unset;
        border-right-color: unset;
        border-bottom-color: unset;
    }

    & hr {
        @apply border-gray-800;
        border-right-color: unset;
        border-bottom-color: unset;
        border-left-color: unset;
    }

    & strong {
        @apply text-white;
    }

    & figure figcaption {
        @apply text-gray-500;
    }

    & a {
        @apply text-white;
    }

    & th {
        @apply text-white;
    }

    & h1, & h2, & h3, & h4 {
        color: white;
    }

    & code {
        @apply text-gray-300;

        &:before {
            @apply text-gray-300;
        }
        
        &:after {
            @apply text-gray-300;
        }
    }

    & ol > li:before {
        @apply text-gray-400;
    }

    & ul > li:before {
        @apply text-gray-600;
    }
}
```
